name: Build images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda_version: [11.7]
        torch_version: [1.13.1]
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/torch:${{ matrix.cuda_version }}
          build-args: |
            BASE=hieupth/mamba
            TORCH_VERSION=${{ matrix.torch_version }}
            CUDA_VERSIOn=${{ matrix.cuda_version }}